# Generated by Django 4.1.4 on 2022-12-23 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='product_db',
        ),
    ]
